sudo: required
services:
  - docker

before_install:
  - docker build -t omripeer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true omripeer/react-test npm test -- --coverage

after_success:
  - docker build -t omripeer/multi-client ./client
  - docker build -t omripeer/multi-nginx ./nginx
  - docker build -t omripeer/multi-server ./server
  - docker build -t omripeer/multi-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push omripeer/multi-client
  - docker push omripeer/multi-nginx
  - docker push omripeer/multi-server
  - docker push omripeer/multi-worker
